(define client_id "heinzelmann")
(define broker_addr "my.broker.address")
(define broker_port 1883)
(define broker_user "user")
(define broker_pass "password")
(define program_location "examples/hs100.scm")
