(define client-id "heinzelmann")
(define broker-addr "my.broker.address")
(define broker-port 1883)
(define broker-user "user")
(define broker-pass "password")
(define program-location "examples/hs100.scm")
(define local-repl #t)
(define nrepl (list "127.0.0.1"))
